workflows:
  android-workflow:
    name: Yemen Market Flex Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          # البناء بدون tree-shake لتجنب مشاكل الأيقونات في البيئات السحابية
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - almwldahmed199@gmail.com
