workflows:
  default-workflow:
    name: Yemen Market Flex Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build APK for Yemen Market
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
